main:
  - { identifier: home, name: Home, url: /en/, weight: 10 }

topnav:
  - { weight: 10, name: Home, pageRef: /, pre: '<img src="/img/home.svg" width="20" alt="Home">' }
  - { weight: 10, name: Membership, pageRef: /pages/membership, alt="Membership">' }
  - { weight: 20, name: Play, pageRef: / }
  - { parent: Play, weight: 21, name: Club Schedule, pageRef: /pages/schedule }
  - { parent: Play, weight: 22, name: Tournaments & Events, pageRef: /events }
  - { parent: Play, weight: 26, name: Lessons, pageRef: /pages/lessons }
  - { parent: Play, weight: 27, name: Chess For Kids, pageRef: /pages/chess-for-kids }
  - { parent: Play, weight: 28, name: Champions, pageRef: /pages/champions }
  - { weight: 30, name: About, pageRef: / }
  - { parent: About, weight: 31, name: Rules, url: '/docs/MCCRulesandRegulationsJan132020.pdf' }
  - { parent: About, weight: 41, name: Sponsors, pageRef: /pages/sponsors }
  - { parent: About, weight: 42, name: Links, pageRef: /pages/links }
  - { parent: About, weight: 60, name: Volunteer, pageRef: /pages/volunteer }
  - { parent: About, weight: 99, name: Contact Us, pageRef: /pages/contact }
  - { parent: About, weight: 101, name: Committee, pageRef: /committee }
